# Generated by Django 4.1.5 on 2023-12-01 07:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_image_name_remove_image_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=base.models.user_directory_path
            ),
        ),
    ]
